- hosts: webservers
  remote_user: tomcat
  become_method: sudo
  vars:
  - warName:  sparkjava-hello-world-1.0.war
  - warRemotePath: /tmp/artifact
  - source: /tmp/artifact/sparkjava-hello-world-1.0.war
  - deploymentpath: /opt/tomcat/webapps/sparkjava-hello-world-1.0.war
  - warLocalPath: /var/lib/jenkins/workspace/infracode/deploymentscripts/artifact 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
  
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
   
  - name: Copy file 
    copy:
      remote_src: /tmp/artifact/sparkjava-hello-world-1.0.war
      dest: /opt/tomcat/webapps/sparkjava-hello-world-1.0.war

  - name: Restart Tomcat
    service:
      name: tomcat
      state: restarted
