- hosts: tomcatServer
  vars:
  - warName: spring-petclinic-2.2.0.BUILD-SNAPSHOT.ja
  - warRemotePath: /tmp/artifact

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}

  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/opt/tomcat/webapps/ROOT/ copy=no mode=0755 owner=tomcat group=tomcat
    notify:
        - Restart tomcat7

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat7
      service: name=tomcat7 state=restarted
