- hosts: webservers
  remote_user: tomcat
  become_method: sudo
  vars:
  - warName:  sparkjava-hello-world-1.0.war
  - warRemotePath: /tmp/artifact
  - deploymentpath: /opt/tomcat/webapps/sparkjava-hello-world-1.0.war
  - warLocalPath: /var/lib/jenkins/workspace/infracode/deploymentscripts/artifact 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
  
  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
   
  - name: Copy file 
    copy:
    src: {{ warRemotePath }}/{{ warName }}
    dest: {{ deploymentpath }} 

- name: enable tomcat startup
    systemd:
    name: tomcat
    enabled: yes
    state: restarted
    become: true
