- hosts: webservers
  remote_user: tomcat
  become_method: sudo
  vars:
  - warName:  PetClinic.war
  - warRemotePath: /tmp/artifact
  - source: /tmp/artifact/PetClinic.war
  - deploymentpath: /opt/tomcat/webapps/PetClinic.war
  - warLocalPath: /var/lib/jenkins/workspace/infracode/deploymentscripts/artifact 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
 
  - name: Delete remote war file
    file: path=/opt/tomcat/webapps/sparkjava-hello-world-1.0.war state=absent
 
  - name: Copy file 
    copy:
      src: /tmp/artifact/PetClinic.war
      dest: /opt/tomcat/webapps/PetClinic.war
      remote_src: yes
    
  - name: restart tomcat
    command: sudo service tomcat restart
