- hosts: webservers
  remote_user: tomcat
  vars:
  - warName:  sparkjava-hello-world-1.0.war
  - warRemotePath: /tmp/artifact
  - warLocalPath: /var/lib/jenkins/workspace/infracode/deploymentscripts/artifact 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest=/opt/tomcat/webapps/ROOT/{{ warName }}

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
