- hosts: webservers
  remote_user: tomcat
  become_method: sudo
  vars:
  - warName:  sparkjava-hello-world-1.0.war
  - warRemotePath: /tmp/artifact
  - warLocalPath: /var/lib/jenkins/workspace/infracode/deploymentscripts/artifact 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
    
  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/opt/tomcat/webapps/ copy=no mode=0755 owner=tomcat group=root
    notify:
        - Restart tomcat

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent

  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
