- hosts: webservers
  remote_user: tomcat
  become_method: sudo
  vars:
  - warName:  simple-spring-webap-1.0.war
  - warRemotePath: /opt/artifact
  - source: /opt/artifact/simple-spring-webapp-1.0.war
  - deploymentpath: /opt/tomcat/webapps/simple-spring-webapp-1.0.war
  - warLocalPath: /var/lib/jenkins/workspace/shared_library_job 

  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}
 
  - name: Delete remote war file
    file: path=/opt/tomcat/webapps/simple-spring-webapp-1.0.war state=absent
 
  - name: Copy file 
    copy:
      src: /opt/artifact/simple-spring-webapp-1.0.war
      dest: /opt/tomcat/webapps/simple-spring-webapp-1.0.war
      remote_src: yes
    
  - name: restart tomcat
    command: sudo service tomcat restart
