- hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
 
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present
      
  - name: tomcat8
    apt:
      name: tomcat8
      state: present

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat8
      state: started
      enabled: true
      daemon_reload: true
